### ISSUE TITLE
Remove FAM from na_trigs.json

### ISSUE THREAD

**Issue by vilijajoyce** [suzytamang/clever-rockies#100]
**Original Request**

> Per Esther 10/3/24, "I noticed on CLEVER-Rockies that the NA triggers for CONNECT includes FAM. This should not be. Many terms related to CONNECT have a Familiar in their context rendering many of those snippets Not Applicable. With the next update could this be changed as well?"

**Action Requested**

Remove FAM for CONNECT in na_trigs.json

- [x] Update 
```"CONNECT": ["FAM"]```
to
```"CONNECT": []```
in na_trigs.json

**Requestor**

3ST Team

**Additional Actions**

- #101
- #102

**Comment by dax-westerman** [comment]
"CONNECT": ["FAM"], updated

![image](https://github.com/user-attachments/assets/ba0cbd2a-5996-4299-a6b3-904725eb7a0f)

**Comment by dax-westerman** [comment]
Converted the Validate and Update delver-rockies SOPs to separate issues.

**Comment by vilijajoyce** [comment]
> "CONNECT": ["FAM"], updated
> 
> ![image](https://private-user-images.githubusercontent.com/11837526/373818870-ba0cbd2a-5996-4299-a6b3-904725eb7a0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMDE2OTYsIm5iZiI6MTcyOTIwMTM5NiwicGF0aCI6Ii8xMTgzNzUyNi8zNzM4MTg4NzAtYmEwY2JkMmEtNTk5Ni00Mjk5LWE2YjMtOTA0NzI1ZWI3YTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDIxNDMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4MmQ0MDNlNWQ0NzkxNmMyOWE3M2ZhN2E5Y2VlMzRkMGQ3ZDBiMjUzMjZkZDkyZmMxZDFiMWY3M2UyYjc0MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YRCEmPd21s2BC5R_KxaHhh95DpAi3xgwG5GzFP2GbVU)

@dax-westerman Please remove quotes contained within the bracket - 
```"CONNECT": []```
TIA!

**Comment by dax-westerman** [comment]
Foremost, thank you for that catch: oversight on my part.  Also, thank you for providing a great example of a validation test!
