### ISSUE TITLE
Delete notebooks directory ASAP

### ISSUE THREAD

**Issue by vilijajoyce** [suzytamang/clever-rockies#109]
Per 20241021 10 AM meeting w/ Stringer, ST, VJ, delete notebooks directory immediately. VJ does not have ability to give Stringer permission to do this for the clever-rockies repo. Seeking help from @dax-westerman .

**Comment by dax-westerman** [comment]
Proceeding with the following steps:
1) clone mirror of CLEVER-Rockies to backup (abundance-of-caution SOP)
2) clone mirror of CLEVER-Rockes for operation
3) Remove notebooks directory from local/cache/reflog
4) Expire reflog and run git gc to clean up packs
5) clone second copy to validate changes
6) push results back to CLEVER-Rockies

**Comment by dax-westerman** [comment]
The **notebooks** folder has been completed.  I had to take a slightly different approach to accommodate historical references to PRs, but otherwise the branches should be cleaned.  If we should spot this later on because of a re-commit of lingering reference on someone else's clone of the repo, I can re-run the cleaning task.

**Comment by dax-westerman** [comment]
@vilijajoyce since this can't be reviewed via PR, would you mind glancing through the **main** to make sure it looks fine.  The next pull for everyone will report merged changes, which is fine.  If anyone encounters any issues, I can assist.

**Comment by dax-westerman** [comment]
I tested a pull into a copy I had from earlier, and the notebook got re-introduced.  Re-fixing.

**Comment by dax-westerman** [comment]
_Now_ it's cleaned up.  The thing I reported might happen, I accidentally did myself.  I checked through different branches, and notebooks isn't present.

**Comment by dax-westerman** [comment]
@vilijajoyce since this can't be reviewed by PR, can you close, please, if you deem this complete?

**Comment by vilijajoyce** [comment]
Thank you for taking care of this @dax-westerman - closed.
