### ISSUE TITLE
Update dict.txt - remove xylazine terms

### ISSUE THREAD

**Issue by vilijajoyce** [suzytamang/clever-rockies#19]
For CLEVER 2.1 release, remove the following rows (terms) from dict.txt
- [x] 3001|tranq|XYLA|drug
- [x] 3002|tranq dope|XYLA|drug
- [x] 3003|zylazine|XYLA|drug

Also
- [x] Renumber
- [x] Validate

**Comment by dax-westerman** [comment]
Migrated to VA
