### ISSUE TITLE
Update to triggers

### ISSUE THREAD

**Issue by dax-westerman** [suzytamang/clever-rockies#37]
In speaking with Viljia, it appears the triggers need to be updated before updating staging.

From her response:

![image](https://github.com/user-attachments/assets/da64692d-a2d5-4a7c-b2a5-ab8a4fc55906)

- This may have an additional component involving COVID entries.  
- Will follow up with additional issue or edit to this one.

**Remove COVID from code**
- [x] #53
- [x] #55
- [x] #57
- [x] #59
- [x] #61
- [x] #62
- [x] Remove COVID from step5.sh (COVID not mentioned in step5. No edits needed.)

**Update base classes**
- [x] #64
- [x] #66

**Comment by vilijajoyce** [comment]
@dax-westerman Here are my proposed edits. I'm open to taking these on if you're comfortable with this and per @suzytamang 's approval:

**Remove COVID from code**
- [ ] Remove COVID terms from dict.txt (records 2000 through 2161)
- [ ] Remove COVID line from na_trigs.json
- [ ] Remove COVID line from neg_trigs.json
- [ ] Remove COVID line from step3.sh
- [ ] Remove COVID lines (76-77) from step2.sh

**Update base classes**
- [ ] Update neg_trigs.json using table above (see triggers associated with "Negative" label)
- [ ] update na_trigs.json using table above (see triggers associated with "NA" label)
- [ ] @suzytamang Aside from the above, is there anything else we need to do to make sure that we have correctly nested the base class triggers under the **positive** label? I didn't see a "pos_trigs.json" file.

**Comment by dax-westerman** [comment]
@vilijajoyce I'm still in a holding pattern for triggering the run, which limits testing, but I have some suggestions as it pertains to the workflow that should help work best here.  I will return to this issues with an update shortly.

**Comment by vilijajoyce** [comment]
Close #75
