### ISSUE TITLE
Remove CA_SYMPTOMS from na_trigs.json and neg_trigs.json files

### ISSUE THREAD

**Issue by vilijajoyce** [suzytamang/clever-rockies#96]
While validating the latest CLEVER run, I noticed that CA_SYMPTOM still appears in na_trigs.json and neg_trigs.json. @dax-westerman - would you like me to take care of this?
- [x] Remove CA_SYMPTOM from na_trigs.json
- [x] Remove CA_SYMPTOM from neg_trigs.json

**Comment by dax-westerman** [comment]
Thanks for the heads up, I'll take care of this now.

**Comment by dax-westerman** [comment]
Completed and merged into main
